name: memotile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl:
  flutter: 
    sdk: flutter
  table_calendar: ^3.0.9
  get_storage: ^2.1.1
  sqflite: ^2.2.8+2
  path: ^1.8.3
  rect_getter: ^1.1.0
  syncfusion_flutter_calendar: ^21.2.9
  flutter_local_notifications: ^14.1.1
#  flutter_native_timezone: ^2.0.0
  flutter_app_badger: ^1.5.0
  flutter_shake_animated: ^0.0.5
  animated_text_kit: ^4.2.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

